branch-defaults:
  default:
    environment: my-backend-env
    group_suffix: null
  main:
    environment: my-backend-env
global:
  application_name: online-portfolio-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
